services:
  scanner:
    build: scanner
    volumes:
      - ./scanner_data:/data
      - ./scan.sh:/root/scan.sh:ro
    restart: always
    depends_on:
      - clash
    entrypoint: ["./scan.sh"]

  clash:
    image: dreamacro/clash
    volumes:
      - ./initial_config.yaml:/root/.config/clash/config.yaml:ro
    ports:
      - 7890:7890
      - 9090:9090
    restart: always

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./scanner_data/alive_proxies.txt:/usr/share/nginx/html/proxies.txt
    ports:
      - 80:80
    restart: always

